version = 2
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
type = "path"
style = "powerline"
foreground = "blue"
background = "transparent"

[blocks.segments.properties]
style = "full"

[[blocks.segments]]
type = "git"
style = "powerline"
powerline_symbol = ""
foreground = "blue"
background = "transparent"
foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}red{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}",
  "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
  "{{ if gt .Behind 0 }}#B388FB{{ end }}"
]
template = "{{ .UpstreamIcon }} {{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }}"

[blocks.segments.properties]
branch_icon = ""
fetch_status = true
fetch_upstream_icon = true
source = "cli"

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
type = "text"
style = "powerline"
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]
background = "transparent"
template = "❯ "

[palette]
green = "#00ff00"

[transient_prompt]
foreground_templates = [
  "{{if gt .Code 0}}red{{end}}",
  "{{if eq .Code 0}}magenta{{end}}",
]
background = "transparent"
template = "❯"
