---
- name: Install Ubuntu Packages
  ansible.builtin.apt:
    state: present
    name: "{{ item }}"
  loop: "{{ ubuntu_packages }}"

- name: Download VS Code Deb Package
  get_url:
    url: https://code.visualstudio.com/sha/download?build=stable&os=linux-deb-x64
    dest: code.deb

- name: Install VS Code
  ansible.builtin.apt:
    deb: code.deb
