---
  - name: Install Ubuntu Packages
    ansible.builtin.apt:
      state: present
      name: "{{ item }}"
    loop: "{{ ubuntu_packages }}"
  - name: Download VS Code Deb Package
    get_url:
      url: https://az764295.vo.msecnd.net/stable/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/code_1.52.1-1608136922_amd64.deb
      dest: code.deb
  - name: Install VS Code
    ansible.builtin.apt:
      deb: code.deb